### ISSUE TITLE
pip3 install shift-detect give couldnot find a version error

### ISSUE THREAD

**Issue by rpaudel42** [paolodedios/shift-detect#1]
I tried to install it using pip3 install shift-detect

But it throw following error. Do you know what dependency requirement it has that do not get installed using pip3?

_Collecting shift-detect
  Could not find a version that satisfies the requirement shift-detect (from versions: )
No matching distribution found for shift-detect_

**Comment by paolodedios** [comment]
I have yet to publish compiled binaries to PyPi. The best way to integrate the shift-detect library is to first install [pybuilder](https://github.com/pybuilder/pybuilder), and then run 

```bash
$ pyb
```

To build the python wheel and then install install the wheel via pip.  The current README references an internal PyPi repository that I deploy wheel deployments into.  I will update the README to reflect that fact.
