### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by chenxingqiang** [paolodedios/shift-detect#2]

**Comment by chenxingqiang** [comment]
your code at shift-detect/src/main/python/shift_detect/rulsif.py:239 

<img width="306" alt="image" src="https://user-images.githubusercontent.com/12387235/53462642-82217880-3a7f-11e9-9fb3-dd9cce86a862.png">

**Comment by chenxingqiang** [comment]
G = sum((samples * samples),  1) should be 
     G = numpy.sum((samples * samples), axis = 1)

**Comment by chenxingqiang** [comment]
@paolodedios please update your code.I have check it by use ariginal matlab RULSIF code.

**Comment by paolodedios** [comment]
Fixed. Thank you.
