### ISSUE TITLE
bug_report 2 

### ISSUE THREAD

**Issue by chenxingqiang** [paolodedios/shift-detect#3]
https://github.com/paolodedios/shift-detect/blob/master/src/main/python/shift_detect/rulsif.py:351
      
 for lambdaIdx in numpy.r_[0:numpy.size(numpy.lambdaCandidates)] : 

should be 

for lambdaIdx in numpy.r_[0:numpy.size(lambdaCandidates)] :

**Comment by chenxingqiang** [comment]
@paolodedios thanks

**Comment by paolodedios** [comment]
Fixed.  Thanks again for the code audit and testing.

> https://github.com/paolodedios/shift-detect/blob/master/src/main/python/shift_detect/rulsif.py:351
> 
> for lambdaIdx in numpy.r_[0:numpy.size(numpy.lambdaCandidates)] :
> 
> should be
> 
> for lambdaIdx in numpy.r_[0:numpy.size(lambdaCandidates)] :
